# Even Fibonacci numbers
# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
# first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence
# whose values do not exceed four million, find the sum of the even-valued terms.
#

fib = Enumerator.new { |y|
  a = b = 1
  loop {
    y << a
    a, b = b, a + b
  }
}

p fib.take_while { |x| x <= 4_000_000 }.select { |x| x % 2 == 0 }.inject { |sum,x| sum + x }
p "DONE"
